### PR TITLE
Vitaliy tolochniy labs 1/2

### PR DESCRIPTION
**Pull request by Vitaliy-Kovalevskiy**

### CODE REVIEW

**Comment by sen-den** [comment]
Comments for https://github.com/kipiek-ksu/programming-141-2020/pull/18 is still valid.

**Review by sen-den — APPROVED** [review]
It is not a good practice to close PR with comments and reopen with the same changes.

**Comment by andxzrey** [comment]
you should make an empty line at the end of the code in the future

**Review by andxzrey — COMMENTED** [review]
ok

**Review by andxzrey — APPROVED** [review]

**Pull request merged**
